/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Comment: typeof import('./components/Comment.vue')['default']
    CourseDetail: typeof import('./components/CourseDetail.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    IndexBlog: typeof import('./components/IndexBlog.vue')['default']
    IndexBlogComponent: typeof import('./components/IndexBlogComponent.vue')['default']
    IndexVideo: typeof import('./components/IndexVideo.vue')['default']
    IndexVideoComponent: typeof import('./components/IndexVideoComponent.vue')['default']
    MaterialCarousel: typeof import('./components/MaterialCarousel.vue')['default']
    MaterialCarouselComponent: typeof import('./components/MaterialCarouselComponent.vue')['default']
    MaterialRecommendCom: typeof import('./components/MaterialRecommendCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheSideBar: typeof import('./components/TheSideBar.vue')['default']
    TheVideo: typeof import('./components/TheVideo.vue')['default']
  }
}
